// Auto-generated product catalog (categories, brand, ON- product codes and page links)
const CATALOG = [
  {"slug":"aires-acondicionados","nameEs":"Aires acondicionados","nameEn":"Air Conditioners","products":[
    {"id":"ir123crs","name":"Aire acondicionado Split Inverter Carnival convertible 5 en 1, 1 T, 3 estrellas","image":"assets/products/ir123crs-1.webp","code":"ON-IR123CRS","brand":"Onida Japan","url":"product-ir123crs.html"},
    {"id":"ir123elg","name":"Aire acondicionado Split Inverter Elegance convertible 5 en 1, 1 T, 3 estrellas","image":"assets/products/ir123elg-1.webp","code":"ON-IR123ELG","brand":"Onida Japan","url":"product-ir123elg.html"},
    {"id":"ir183elg","name":"Aire acondicionado Split Inverter Elegance convertible 5 en 1, 1,5 T, 3 estrellas","image":"assets/products/ir183elg-1.webp","code":"ON-IR183ELG","brand":"Onida Japan","url":"product-ir183elg.html"},
    {"id":"ir204evs","name":"Aire acondicionado Split Inverter Everest convertible 5 en 1 con Wi-Fi, 1,6 T Plus, 4 estrellas","image":"assets/products/ir204evs-1.webp","code":"ON-IR204EVS","brand":"Onida Japan","url":"product-ir204evs.html"},
    {"id":"ir253evs","name":"Aire acondicionado Split Inverter Everest convertible 5 en 1, 2 T, 3 estrellas","image":"assets/products/ir253evs-1.webp","code":"ON-IR253EVS","brand":"Onida Japan","url":"product-ir253evs.html"},
    {"id":"ir183flcv","name":"Aire acondicionado Split Inverter Falcon convertible 9 en 1, 1,5 T, 3 estrellas","image":"assets/products/ir183flcv-1.webp","code":"ON-IR183FLCV","brand":"Onida Japan","url":"product-ir183flcv.html"},
    {"id":"ir243flcv","name":"Aire acondicionado Split Inverter Falcon convertible 9 en 1, 2 T, 3 estrellas (IR243FLCV)","image":"assets/products/ir243flcv-1.webp","code":"ON-IR243FLCV","brand":"Onida Japan","url":"product-ir243flcv.html"},
    {"id":"ir243flrv","name":"Aire acondicionado Split Inverter Falcon convertible 9 en 1, 2 T, 3 estrellas (IR243FLRV)","image":"assets/products/ir243flrv-1.webp","code":"ON-IR243FLRV","brand":"Onida Japan","url":"product-ir243flrv.html"},
    {"id":"ir123fis","name":"Aire acondicionado Split Inverter Fiesta convertible 5 en 1, 1 T, 3 estrellas","image":"assets/products/ir123fis-1.webp","code":"ON-IR123FIS","brand":"Onida Japan","url":"product-ir123fis.html"},
    {"id":"ir195glc","name":"Aire acondicionado Split Inverter Gale convertible 5 en 1, 1,5 T, 5 estrellas","image":"assets/products/ir195glc-1.webp","code":"ON-IR195GLC","brand":"Onida Japan","url":"product-ir195glc.html"},
    {"id":"ir123grps","name":"Aire acondicionado Split Inverter Gloria NX convertible 5 en 1, 1 T, 3 estrellas","image":"assets/products/ir123grps-1.webp","code":"ON-IR123GRPS","brand":"Onida Japan","url":"product-ir123grps.html"},
    {"id":"ir183grps","name":"Aire acondicionado Split Inverter Gloria Refresh convertible 5 en 1, 1,5 T, 3 estrellas (IR183GRPS)","image":"assets/products/ir183grps-1.webp","code":"ON-IR183GRPS","brand":"Onida Japan","url":"product-ir183grps.html"},
    {"id":"ir195grps","name":"Aire acondicionado Split Inverter Gloria Refresh convertible 5 en 1, 1,5 T, 3 estrellas (IR195GRPS)","image":"assets/products/ir195grps-1.webp","code":"ON-IR195GRPS","brand":"Onida Japan","url":"product-ir195grps.html"},
    {"id":"ir123mgcp","name":"Aire acondicionado Split Inverter Magnus convertible 5 en 1, 1 T, 3 estrellas","image":"assets/products/ir123mgcp-1.webp","code":"ON-IR123MGCP","brand":"Onida Japan","url":"product-ir123mgcp.html"},
    {"id":"ir193mgcp","name":"Aire acondicionado Split Inverter Magnus convertible 5 en 1, 1,5 T, 3 estrellas","image":"assets/products/ir193mgcp-1.webp","code":"ON-IR193MGCP","brand":"Onida Japan","url":"product-ir193mgcp.html"},
    {"id":"ir185mgcp","name":"Aire acondicionado Split Inverter Magnus convertible 5 en 1, 1,5 T, 5 estrellas","image":"assets/products/ir185mgcp-1.webp","code":"ON-IR185MGCP","brand":"Onida Japan","url":"product-ir185mgcp.html"},
    {"id":"ir123mjs","name":"Aire acondicionado Split Inverter Majestic convertible 5 en 1, 1 T, 3 estrellas","image":"assets/products/ir123mjs-1.webp","code":"ON-IR123MJS","brand":"Onida Japan","url":"product-ir123mjs.html"},
    {"id":"ir183mjs","name":"Aire acondicionado Split Inverter Majestic convertible 5 en 1, 1,5 T, 3 estrellas (IR183MJS)","image":"assets/products/ir183mjs-1.webp","code":"ON-IR183MJS","brand":"Onida Japan","url":"product-ir183mjs.html"},
    {"id":"ir193mjs","name":"Aire acondicionado Split Inverter Majestic convertible 5 en 1, 1,5 T, 3 estrellas (IR193MJS)","image":"assets/products/ir193mjs-1.webp","code":"ON-IR193MJS","brand":"Onida Japan","url":"product-ir193mjs.html"},
    {"id":"ir195mjs","name":"Aire acondicionado Split Inverter Majestic convertible 5 en 1, 1,5 T, 5 estrellas","image":"assets/products/ir195mjs-1.webp","code":"ON-IR195MJS","brand":"Onida Japan","url":"product-ir195mjs.html"},
    {"id":"ir243mjs","name":"Aire acondicionado Split Inverter Majestic convertible 5 en 1, 2 T, 3 estrellas","image":"assets/products/ir243mjs-1.webp","code":"ON-IR243MJS","brand":"Onida Japan","url":"product-ir243mjs.html"},
    {"id":"ir195oys","name":"Aire acondicionado Split Inverter Olympus convertible 5 en 1, 1,5 T, 5 estrellas","image":"assets/products/ir195oys-1.webp","code":"ON-IR195OYS","brand":"Onida Japan","url":"product-ir195oys.html"},
    {"id":"ir203oys","name":"Aire acondicionado Split Inverter Olympus convertible 5 en 1, 1,6 T, 3 estrellas","image":"assets/products/ir203oys-1.webp","code":"ON-IR203OYS","brand":"Onida Japan","url":"product-ir203oys.html"},
    {"id":"ir183rgs","name":"Aire acondicionado Split Inverter Rio convertible 5 en 1, 1,5 T, 3 estrellas (IR183RGS)","image":"assets/products/ir183rgs-1.webp","code":"ON-IR183RGS","brand":"Onida Japan","url":"product-ir183rgs.html"},
    {"id":"ir193rgs","name":"Aire acondicionado Split Inverter Rio convertible 5 en 1, 1,5 T, 3 estrellas (IR193RGS)","image":"assets/products/ir193rgs-1.webp","code":"ON-IR193RGS","brand":"Onida Japan","url":"product-ir193rgs.html"},
    {"id":"ir243rgs","name":"Aire acondicionado Split Inverter Rio convertible 5 en 1, 2 T, 3 estrellas","image":"assets/products/ir243rgs-1.webp","code":"ON-IR243RGS","brand":"Onida Japan","url":"product-ir243rgs.html"},
    {"id":"ir243tsn1","name":"Aire acondicionado Split Inverter Trendy NX de uso intensivo tropical, 2 T, 3 estrellas","image":"assets/products/ir243tsn1-1.webp","code":"ON-IR243TSN1","brand":"Onida Japan","url":"product-ir243tsn1.html"},
    {"id":"ir183tsn","name":"Aire acondicionado Split Inverter Trendy de uso intensivo tropical, 1,5 T, 3 estrellas","image":"assets/products/ir183tsn-1.webp","code":"ON-IR183TSN","brand":"Onida Japan","url":"product-ir183tsn.html"},
    {"id":"ir195trs","name":"Aire acondicionado Split Inverter Trendy de uso intensivo tropical, 1,5 T, 5 estrellas","image":"assets/products/ir195trs-1.webp","code":"ON-IR195TRS","brand":"Onida Japan","url":"product-ir195trs.html"},
    {"id":"ir183zvs","name":"Aire acondicionado Split Inverter Ziva convertible 5 en 1, 1,5 T, 3 estrellas","image":"assets/products/ir183zvs-1.webp","code":"ON-IR183ZVS","brand":"Onida Japan","url":"product-ir183zvs.html"},
    {"id":"ir185zvc","name":"Aire acondicionado Split Inverter Ziva convertible 5 en 1, 1,5 T, 5 estrellas (IR185ZVC)","image":"assets/products/ir185zvc-1.webp","code":"ON-IR185ZVC","brand":"Onida Japan","url":"product-ir185zvc.html"},
    {"id":"ir185zvs","name":"Aire acondicionado Split Inverter Ziva convertible 5 en 1, 1,5 T, 5 estrellas (IR185ZVS)","image":"assets/products/ir185zvs-1.webp","code":"ON-IR185ZVS","brand":"Onida Japan","url":"product-ir185zvs.html"},
    {"id":"sr243asr","name":"Aire acondicionado Split de velocidad fija Aster, uso intensivo tropical, 2 T Plus, 3 estrellas","image":"assets/products/sr243asr-1.webp","code":"ON-SR243ASR","brand":"Onida Japan","url":"product-sr243asr.html"},
    {"id":"sr123gdc","name":"Aire acondicionado Split de velocidad fija Grandeur, enfriamiento potente, 1 T, 3 estrellas","image":"assets/products/sr123gdc-1.webp","code":"ON-SR123GDC","brand":"Onida Japan","url":"product-sr123gdc.html"},
    {"id":"sr183gdc","name":"Aire acondicionado Split de velocidad fija Grandeur, enfriamiento potente, 1,5 T, 3 estrellas","image":"assets/products/sr183gdc-1.webp","code":"ON-SR183GDC","brand":"Onida Japan","url":"product-sr183gdc.html"},
    {"id":"sr203slr","name":"Aire acondicionado Split de velocidad fija Silk, uso intensivo tropical, 1,6 T, 3 estrellas","image":"assets/products/sr203slr-1.webp","code":"ON-SR203SLR","brand":"Onida Japan","url":"product-sr203slr.html"},
    {"id":"sr252slr","name":"Aire acondicionado Split de velocidad fija Silk, uso intensivo tropical, 2 T Plus, 2 estrellas","image":"assets/products/sr252slr-1.webp","code":"ON-SR252SLR","brand":"Onida Japan","url":"product-sr252slr.html"},
    {"id":"sr183atg","name":"Aire acondicionado Split de velocidad fija Splendor, enfriamiento potente, 1,5 T, 3 estrellas","image":"assets/products/sr183atg-1.webp","code":"ON-SR183ATG","brand":"Onida Japan","url":"product-sr183atg.html"},
    {"id":"sr183vgc","name":"Aire acondicionado Split de velocidad fija Vega, enfriamiento potente, 1,5 T, 3 estrellas","image":"assets/products/sr183vgc-1.webp","code":"ON-SR183VGC","brand":"Onida Japan","url":"product-sr183vgc.html"}
  ]},
  {"slug":"lavadoras","nameEs":"Lavadoras","nameEn":"Washing Machines","products":[
    {"id":"f75tg","name":"Lavadora automática de carga frontal Trendy, 7,5 kg","image":"assets/products/f75tg-1.webp","code":"ON-F75TG","brand":"Onida Japan","url":"product-f75tg.html"},
    {"id":"t65cdn","name":"Lavadora automática de carga superior Black Pearl, 6,5 kg, 5 estrellas","image":"assets/products/t65cdn-1.webp","code":"ON-T65CDN","brand":"Onida Japan","url":"product-t65cdn.html"},
    {"id":"t65cbr","name":"Lavadora automática de carga superior Crystal, 6,5 kg, 5 estrellas","image":"assets/products/t65cbr-1.webp","code":"ON-T65CBR","brand":"Onida Japan","url":"product-t65cbr.html"},
    {"id":"t70cgn","name":"Lavadora automática de carga superior Crystal, 7 kg, 5 estrellas (gris oscuro)","image":"assets/products/t70cgn-1.webp","code":"ON-T70CGN","brand":"Onida Japan","url":"product-t70cgn.html"},
    {"id":"t70fgd","name":"Lavadora automática de carga superior Crystal, 7 kg, 5 estrellas (gris)","image":"assets/products/t70fgd-1.webp","code":"ON-T70FGD","brand":"Onida Japan","url":"product-t70fgd.html"},
    {"id":"t80cgn","name":"Lavadora automática de carga superior Crystal, 7,5 kg, 5 estrellas","image":"assets/products/t80cgn-1.webp","code":"ON-T80CGN","brand":"Onida Japan","url":"product-t80cgn.html"},
    {"id":"t65cgn1","name":"Lavadora automática de carga superior Fabric Care, 6,5 kg, 5 estrellas","image":"assets/products/t65cgn1-1.webp","code":"ON-T65CGN1","brand":"Onida Japan","url":"product-t65cgn1.html"},
    {"id":"t85gdbh","name":"Lavadora automática de carga superior Grandeur con lavado higiénico con agua caliente, 8 kg, 5 estrellas","image":"assets/products/t85gdbh-1.webp","code":"ON-T85GDBH","brand":"Onida Japan","url":"product-t85gdbh.html"},
    {"id":"t85gdb","name":"Lavadora automática de carga superior Grandeur con tecnología Sensomatic, 8 kg, 5 estrellas","image":"assets/products/t85gdb-1.webp","code":"ON-T85GDB","brand":"Onida Japan","url":"product-t85gdb.html"},
    {"id":"w90w","name":"Lavadora de una tina Cyclone, 9 kg (blanco)","image":"assets/products/w90w-1.webp","code":"ON-W90W","brand":"Onida Japan","url":"product-w90w.html"},
    {"id":"w90gr","name":"Lavadora de una tina Cyclone, 9 kg (negro)","image":"assets/products/w90gr-1.webp","code":"ON-W90GR","brand":"Onida Japan","url":"product-w90gr.html"},
    {"id":"ws65lpt1lr","name":"Lavadora de una tina Liliput, 6 kg","image":"assets/products/ws65lpt1lr-1.webp","code":"ON-WS65LPT1LR","brand":"Onida Japan","url":"product-ws65lpt1lr.html"},
    {"id":"w70w","name":"Lavadora de una tina Liliput, 7 kg (blanco)","image":"assets/products/w70w-1.webp","code":"ON-W70W","brand":"Onida Japan","url":"product-w70w.html"},
    {"id":"w70g","name":"Lavadora de una tina Liliput, 7 kg (gris)","image":"assets/products/w70g-1.webp","code":"ON-W70G","brand":"Onida Japan","url":"product-w70g.html"},
    {"id":"s11gs","name":"Lavadora semiautomática Cyclone, 11 kg, 5 estrellas","image":"assets/products/s11gs-1.webp","code":"ON-S11GS","brand":"Onida Japan","url":"product-s11gs.html"},
    {"id":"s12gs1","name":"Lavadora semiautomática Cyclone, 12 kg, 5 estrellas","image":"assets/products/s12gs1-1.webp","code":"ON-S12GS1","brand":"Onida Japan","url":"product-s12gs1.html"},
    {"id":"s14cb","name":"Lavadora semiautomática Cyclone, 14 kg, 5 estrellas","image":"assets/products/s14cb-1.webp","code":"ON-S14CB","brand":"Onida Japan","url":"product-s14cb.html"},
    {"id":"s75scb","name":"Lavadora semiautomática Fabric Care, 7,5 kg, 5 estrellas","image":"assets/products/s75scb-1.webp","code":"ON-S75SCB","brand":"Onida Japan","url":"product-s75scb.html"},
    {"id":"s85ogi","name":"Lavadora semiautomática Fabric Care, 8,5 kg, 5 estrellas","image":"assets/products/s85ogi-1.webp","code":"ON-S85OGI","brand":"Onida Japan","url":"product-s85ogi.html"},
    {"id":"s65ob","name":"Lavadora semiautomática Hydrocare, 6,5 kg, 5 estrellas (azul)","image":"assets/products/s65ob-1.webp","code":"ON-S65OB","brand":"Onida Japan","url":"product-s65ob.html"},
    {"id":"s65tr","name":"Lavadora semiautomática Hydrocare, 6,5 kg, 5 estrellas (red)","image":"assets/products/s65tr-1.webp","code":"ON-S65TR","brand":"Onida Japan","url":"product-s65tr.html"},
    {"id":"s70gr","name":"Lavadora semiautomática Hydrocare, 7 kg, 5 estrellas (gris)","image":"assets/products/s70gr-1.webp","code":"ON-S70GR","brand":"Onida Japan","url":"product-s70gr.html"},
    {"id":"s70tr","name":"Lavadora semiautomática Hydrocare, 7 kg, 5 estrellas (red)","image":"assets/products/s70tr-1.webp","code":"ON-S70TR","brand":"Onida Japan","url":"product-s70tr.html"},
    {"id":"s75grb","name":"Lavadora semiautomática Hydrocare, 7,5 kg, 5 estrellas","image":"assets/products/s75grb-1.webp","code":"ON-S75GRB","brand":"Onida Japan","url":"product-s75grb.html"},
    {"id":"s85gs3","name":"Lavadora semiautomática Hydrocare, 8,5 kg, 5 estrellas (granate y negro)","image":"assets/products/s85gs3-1.webp","code":"ON-S85GS3","brand":"Onida Japan","url":"product-s85gs3.html"},
    {"id":"s85gs2","name":"Lavadora semiautomática Hydrocare, 8,5 kg, 5 estrellas (negro y gris)","image":"assets/products/s85gs2-1.webp","code":"ON-S85GS2","brand":"Onida Japan","url":"product-s85gs2.html"},
    {"id":"s95gs2","name":"Lavadora semiautomática Hydrocare, 9,5 kg, 5 estrellas (S95GS2)","image":"assets/products/s95gs2-1.webp","code":"ON-S95GS2","brand":"Onida Japan","url":"product-s95gs2.html"},
    {"id":"s95gs3","name":"Lavadora semiautomática Hydrocare, 9,5 kg, 5 estrellas (S95GS3)","image":"assets/products/s95gs3-1.webp","code":"ON-S95GS3","brand":"Onida Japan","url":"product-s95gs3.html"},
    {"id":"s70oib","name":"Lavadora semiautomática Smartcare, 7 kg, 5 estrellas (azul)","image":"assets/products/s70oib-1.webp","code":"ON-S70OIB","brand":"Onida Japan","url":"product-s70oib.html"},
    {"id":"s70ogi","name":"Lavadora semiautomática Smartcare, 7 kg, 5 estrellas (red)","image":"assets/products/s70ogi-1.webp","code":"ON-S70OGI","brand":"Onida Japan","url":"product-s70ogi.html"},
    {"id":"s75tib","name":"Lavadora semiautomática Smartcare, 7,5 kg, 5 estrellas","image":"assets/products/s75tib-1.webp","code":"ON-S75TIB","brand":"Onida Japan","url":"product-s75tib.html"},
    {"id":"s80onr","name":"Lavadora semiautomática Smartcare, 8 kg, 5 estrellas (S80ONR)","image":"assets/products/s80onr-1.webp","code":"ON-S80ONR","brand":"Onida Japan","url":"product-s80onr.html"},
    {"id":"s80sbxg","name":"Lavadora semiautomática Smartcare, 8 kg, 5 estrellas (S80SBXG)","image":"assets/products/s80sbxg-1.webp","code":"ON-S80SBXG","brand":"Onida Japan","url":"product-s80sbxg.html"},
    {"id":"s80sbxr","name":"Lavadora semiautomática Smartcare, 8 kg, 5 estrellas (S80SBXR)","image":"assets/products/s80sbxr-1.webp","code":"ON-S80SBXR","brand":"Onida Japan","url":"product-s80sbxr.html"},
    {"id":"s80sctr","name":"Lavadora semiautomática Smartcare, 8 kg, 5 estrellas (S80SCTR)","image":"assets/products/s80sctr-1.webp","code":"ON-S80SCTR","brand":"Onida Japan","url":"product-s80sctr.html"},
    {"id":"s80tbg","name":"Lavadora semiautomática Smartcare, 8 kg, 5 estrellas (S80TBG)","image":"assets/products/s80tbg-1.webp","code":"ON-S80TBG","brand":"Onida Japan","url":"product-s80tbg.html"},
    {"id":"s85sbsxb","name":"Lavadora semiautomática Smartcare, 8 kg, 5 estrellas (S85SBSXB)","image":"assets/products/s85sbsxb-1.webp","code":"ON-S85SBSXB","brand":"Onida Japan","url":"product-s85sbsxb.html"},
    {"id":"s85tib","name":"Lavadora semiautomática Smartcare, 8 kg, 5 estrellas (S85TIB)","image":"assets/products/s85tib-1.webp","code":"ON-S85TIB","brand":"Onida Japan","url":"product-s85tib.html"},
    {"id":"s80gs","name":"Lavadora semiautomática Ultra Wash, 8 kg, 5 estrellas","image":"assets/products/s80gs-1.webp","code":"ON-S80GS","brand":"Onida Japan","url":"product-s80gs.html"}
  ]},
  {"slug":"neveras","nameEs":"Neveras","nameEn":"Refrigerators","products":[
    {"id":"rds1802b","name":"Nevera de una puerta Insta Chill, 180 L, enfriamiento directo, 2 estrellas (RDS1802B)","image":"assets/products/rds1802b-1.webp","code":"ON-RDS1802B","brand":"Onida Japan","url":"product-rds1802b.html"},
    {"id":"rds1802r","name":"Nevera de una puerta Insta Chill, 180 L, enfriamiento directo, 2 estrellas (RDS1802R)","image":"assets/products/rds1802r-1.webp","code":"ON-RDS1802R","brand":"Onida Japan","url":"product-rds1802r.html"},
    {"id":"rds2102bn","name":"Nevera de una puerta Insta Chill, 210 L, enfriamiento directo, 2 estrellas (RDS2102BN)","image":"assets/products/rds2102bn-1.webp","code":"ON-RDS2102BN","brand":"Onida Japan","url":"product-rds2102bn.html"},
    {"id":"rds2102rn","name":"Nevera de una puerta Insta Chill, 210 L, enfriamiento directo, 2 estrellas (RDS2102RN)","image":"assets/products/rds2102rn-1.webp","code":"ON-RDS2102RN","brand":"Onida Japan","url":"product-rds2102rn.html"},
    {"id":"rds2152pn","name":"Nevera de una puerta Insta Chill, 215 L, enfriamiento directo, 2 estrellas (RDS2152PN)","image":"assets/products/rds2152pn-1.webp","code":"ON-RDS2152PN","brand":"Onida Japan","url":"product-rds2152pn.html"},
    {"id":"rds2152sn","name":"Nevera de una puerta Insta Chill, 215 L, enfriamiento directo, 2 estrellas (RDS2152SN)","image":"assets/products/rds2152sn-1.webp","code":"ON-RDS2152SN","brand":"Onida Japan","url":"product-rds2152sn.html"},
    {"id":"rds2302bn","name":"Nevera de una puerta Insta Chill, 230 L, enfriamiento directo, 2 estrellas (RDS2302BN)","image":"assets/products/rds2302bn-1.webp","code":"ON-RDS2302BN","brand":"Onida Japan","url":"product-rds2302bn.html"},
    {"id":"rds2302rn","name":"Nevera de una puerta Insta Chill, 230 L, enfriamiento directo, 2 estrellas (RDS2302RN)","image":"assets/products/rds2302rn-1.webp","code":"ON-RDS2302RN","brand":"Onida Japan","url":"product-rds2302rn.html"},
    {"id":"rds1001sgn","name":"Nevera de una puerta Insta Chill, 92 L, enfriamiento directo, 1 estrella","image":"assets/products/rds1001sgn-1.webp","code":"ON-RDS1001SGN","brand":"Onida Japan","url":"product-rds1001sgn.html"}
  ]},
  {"slug":"enfriadores-de-aire","nameEs":"Enfriadores de aire","nameEn":"Air Coolers","products":[
    {"id":"dc95gbo","name":"Enfriador de aire de desierto Grandeur, 95 L","image":"assets/products/dc95gbo-1.webp","code":"ON-DC95GBO","brand":"Onida Japan","url":"product-dc95gbo.html"},
    {"id":"dc50gwg","name":"Enfriador de aire de desierto Gusto, 50 L","image":"assets/products/dc50gwg-1.webp","code":"ON-DC50GWG","brand":"Onida Japan","url":"product-dc50gwg.html"},
    {"id":"80zdg","name":"Enfriador de aire de desierto Zephyr, 80 L","image":"assets/products/80zdg-1.webp","code":"ON-80ZDG","brand":"Onida Japan","url":"product-80zdg.html"},
    {"id":"95zdg","name":"Enfriador de aire de desierto Zephyr, 95 L","image":"assets/products/95zdg-1.webp","code":"ON-95ZDG","brand":"Onida Japan","url":"product-95zdg.html"},
    {"id":"pc35adg","name":"Enfriador de aire personal Aero, 35 L","image":"assets/products/pc35adg-1.webp","code":"ON-PC35ADG","brand":"Onida Japan","url":"product-pc35adg.html"}
  ]},
  {"slug":"televisores","nameEs":"Televisores","nameEn":"Televisions","products":[
    {"id":"43ugid-r","name":"Televisor Nexg 4K Ultra HD de 43 pulgadas con altavoces KY Rock","image":"assets/products/43ugid-r-1.webp","code":"ON-43UGID-R","brand":"Onida Japan","url":"product-43ugid-r.html"},
    {"id":"55ugid-r","name":"Televisor Nexg 4K Ultra HD de 55 pulgadas con karaoke integrado y altavoces KY Rock","image":"assets/products/55ugid-r-1.webp","code":"ON-55UGID-R","brand":"Onida Japan","url":"product-55ugid-r.html"},
    {"id":"mn100ugw","name":"Televisor QD Mini LED de 100 pulgadas KY Thunder","image":"assets/products/mn100ugw-1.webp","code":"ON-MN100UGW","brand":"Onida Japan","url":"product-mn100ugw.html"}
  ]}
];
